name: Android CI Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Unit & UI Tests
    # Menggunakan macOS agar emulator Android bisa berjalan dengan lancar dan cepat
    runs-on: macos-latest 

    steps:
      # 1. Mengambil kode aplikasimu dari repositori
      - name: Checkout project code
        uses: actions/checkout@v4

      # 2. Menyiapkan Java Development Kit (JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Kamu bisa mengubah angka ini jika projectmu menggunakan Java 11 atau 21
          distribution: 'temurin'
          cache: gradle

      # Memberikan izin eksekusi
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 3. Menjalankan Unit Test murni secara terisolasi
      - name: Run Pure Unit Tests
        run: ./gradlew testDebugUnitTest

      # 4. Menjalankan Android Instrumented Test menggunakan Emulator Virtual
      - name: Run Android Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29 # Menjalankan emulator dengan Android 10 (API 29)
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedDebugAndroidTest
