name: Android Release Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Menggunakan action resmi Gradle untuk caching otomatis
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      # UBAH: Menggunakan assembleRelease untuk build produksi
      - name: Build APK (Parallel & Cached)
        run: ./gradlew assembleRelease --parallel --build-cache --configuration-cache --stacktrace
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

      # --- STEP: Menandatangani Release APK ---
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          # UBAH: Arahkan ke folder release tempat Release APK berada
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # --- STEP: Mengunggah Release APK yang sudah ditandatangani ---
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pos-offline-release-signed-apk
          path: |
            ${{steps.sign_app.outputs.signedReleaseFile}}
            app/**/*.json
          retention-days: 7
