name: Reveal Secret via Artifact

on:
  workflow_dispatch:

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Simpan Secret ke File
        env:
          MY_SECRET: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo "$MY_SECRET" > secret_file.txt

      - name: Upload File ke Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: secret-artifact
          path: secret_file.txt