name: Reveal Secret

on:
  workflow_dispatch: # Agar bisa dijalankan manual dari tombol GitHub

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret as Base64
        env:
          MY_SECRET: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          echo -n "$MY_SECRET" | base64